## 安装kubernetes
- hosts: kuber_and_etcd_and_registry
  remote_user: root
  become: yes
  become_method: sudo
  environment:
    PATH: "{{ ansible_env.PATH }}:{{root_bin}}"

  roles:
    - {
        role: flannel,
        when: inventory_hostname in groups.kuber_node
      }
    - {
        role: docker,
        when: inventory_hostname in groups.kuber_node
      }
    - {
        role: k8s_node,
        when: inventory_hostname in groups.kuber_node
      }