---

- name: 创建sonar模板目录
  file:
    path: "{{one_components_dir}}/sonar"
    state: directory

- name: 上传 sonar 模板
  template:
    src: "../templates/sonar/{{item}}"
    dest: "{{one_components_dir}}/sonar/{{item}}"
    force: true
  with_items:
    - one-sonar-deployment.yml
    - one-sonar-service.yml

- name: 创建sonar服务
  shell: "kubectl create -f {{one_components_dir}}/sonar/."