apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: newtouchone
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: amqp
      port: 5672
    - name: web
      port: 15672