---

- name: 创建newtouchone 命名空间
  shell: kubectl create namespace newtouchone
  ignore_errors: yes

- name: 创建ceph配置目录
  file:
    path: "{{k8s_addon_dir}}/ceph"
    state: directory

- name: 上传cephsecret.yaml
  template:
    src: ../templates/cephsecret.yaml.j2
    dest: "{{k8s_addon_dir}}/ceph/cephsecret.yaml"
    force: true

- name: 创建ceph secret配置
  shell: "kubectl create -f {{k8s_addon_dir}}/ceph/cephsecret.yaml"
