---

- name: 创建heapster服务目录
  file:
    path: "{{k8s_heapster_dir}}"
    state: directory

- name: 上传heapster服务文件
  template: src={{ item }} dest={{k8s_heapster_dir}}/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/heapster/*.j2

- name: 启动heapster服务
  shell: kubectl create -f {{k8s_heapster_dir}}
