apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: newtouchone
  labels:
    app: sonar
spec:
  selector:
    app: sonar
  type: NodePort
  ports:
  - name: web0
    port: 9000
  - name: web1
    port: 9092