apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar
  namespace: newtouchone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar
    spec:
      hostname: sonar
      containers:
      - name: sonar
        image: {{ hostvars[groups['registry'][0]]['ansible_eth0']['ipv4']['address'] }}:5000/newtouchone/sonarqube:6.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        - containerPort: 9092